# Generated by Django 4.1.6 on 2023-02-18 19:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=225, unique=True)),
                ('videosList', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
