# Generated by Django 4.1.6 on 2023-02-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_module_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
